--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ULTRAS
--------------------------------------------------------

  CREATE TABLE "HR"."ULTRAS" 
   (	"ULTRAS_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DNI" VARCHAR2(15 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."ULTRAS"."ULTRAS_ID" IS 'IDENTIFICADOR DE ULTRAS';
   COMMENT ON COLUMN "HR"."ULTRAS"."NOMBRE" IS 'IDENTIFCICACION DE ULTRAS';
   COMMENT ON COLUMN "HR"."ULTRAS"."DNI" IS 'DOCUMENTACION DE ULTRAS';
   COMMENT ON COLUMN "HR"."ULTRAS"."FECHA_NACIMIENTO" IS 'FECHA DE NACIMIENTO DE ULTRAS';
   COMMENT ON COLUMN "HR"."ULTRAS"."AFICION_ID" IS 'IDENTIFICADOR DE AFICION';
REM INSERTING into HR.ULTRAS
SET DEFINE OFF;
Insert into HR.ULTRAS (ULTRAS_ID,NOMBRE,DNI,FECHA_NACIMIENTO,AFICION_ID) values ('1','MARIO LUX','55516456G',to_date('07/06/90','DD/MM/RR'),'1');
Insert into HR.ULTRAS (ULTRAS_ID,NOMBRE,DNI,FECHA_NACIMIENTO,AFICION_ID) values ('2','LUCAS NULO','55514734M',to_date('13/12/85','DD/MM/RR'),'2');
Insert into HR.ULTRAS (ULTRAS_ID,NOMBRE,DNI,FECHA_NACIMIENTO,AFICION_ID) values ('3','EMILIO MASS','55513749G',to_date('27/02/93','DD/MM/RR'),'1');
Insert into HR.ULTRAS (ULTRAS_ID,NOMBRE,DNI,FECHA_NACIMIENTO,AFICION_ID) values ('4','RICARDO PARTY','55516438G',to_date('26/05/89','DD/MM/RR'),'1');
--------------------------------------------------------
--  DDL for Index ULTRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ULTRAS_PK" ON "HR"."ULTRAS" ("ULTRAS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ULTRAS
--------------------------------------------------------

  ALTER TABLE "HR"."ULTRAS" ADD CONSTRAINT "ULTRAS_PK" PRIMARY KEY ("ULTRAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ULTRAS" MODIFY ("ULTRAS_ID" NOT NULL ENABLE);
